

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "PlayingTable.xaml.h"




void ::BlackjackClient::PlayingTable::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///PlayingTable.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///PlayingTable.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Grid named 'LayoutRoot'
    LayoutRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"LayoutRoot"));
    // Get the Grid named 'dealerGrid'
    dealerGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"dealerGrid"));
    // Get the TextBlock named 'resultLabel'
    resultLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"resultLabel"));
    // Get the AppBar named 'TopBar'
    TopBar = safe_cast<::Windows::UI::Xaml::Controls::AppBar^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"TopBar"));
    // Get the AppBar named 'BottomBar'
    BottomBar = safe_cast<::Windows::UI::Xaml::Controls::AppBar^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BottomBar"));
    // Get the Button named 'exitButton'
    exitButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"exitButton"));
    // Get the Button named 'joinButton'
    joinButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"joinButton"));
    // Get the Button named 'leaveButton'
    leaveButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"leaveButton"));
    // Get the TextBox named 'serverAddress'
    serverAddress = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"serverAddress"));
    // Get the TextBox named 'playerName'
    playerName = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"playerName"));
    // Get the Grid named 'playerGrid'
    playerGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"playerGrid"));
    // Get the StackPanel named 'playerPanel'
    playerPanel = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"playerPanel"));
    // Get the TextBlock named 'hitButton'
    hitButton = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"hitButton"));
    // Get the TextBlock named 'stayButton'
    stayButton = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"stayButton"));
    // Get the TextBlock named 'doubleButton'
    doubleButton = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"doubleButton"));
    // Get the TextBlock named 'button1'
    button1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"button1"));
    // Get the TextBlock named 'label1'
    label1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"label1"));
    // Get the TextBox named 'betBox'
    betBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"betBox"));
    // Get the TextBlock named 'buyInsuranceButton'
    buyInsuranceButton = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"buyInsuranceButton"));
    // Get the TextBlock named 'buyInsuranceLabel'
    buyInsuranceLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"buyInsuranceLabel"));
    // Get the TextBox named 'buyInsuranceTextBox'
    buyInsuranceTextBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"buyInsuranceTextBox"));
}

void ::BlackjackClient::PlayingTable::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::BlackjackClient::PlayingTable::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&PlayingTable::ExitButton_Click);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::BlackjackClient::PlayingTable::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&PlayingTable::JoinButton_Click);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::BlackjackClient::PlayingTable::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&PlayingTable::LeaveButton_Click);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::BlackjackClient::PlayingTable::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&PlayingTable::HitButton_Click);
        break;
    case 5:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::BlackjackClient::PlayingTable::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&PlayingTable::StayButton_Click);
        break;
    case 6:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::BlackjackClient::PlayingTable::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&PlayingTable::DoubleButton_Click);
        break;
    case 7:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::BlackjackClient::PlayingTable::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&PlayingTable::BetButton_Click);
        break;
    case 8:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->Tapped +=
            ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::BlackjackClient::PlayingTable::*)(Platform::Object^, Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&PlayingTable::InsuranceButton_Click);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

